# Phase 2 — Dataset Collection & Exploration
### Medical Insurance Cost Prediction

In this phase, we load the **Medical Cost Personal Dataset** using Pandas and explore its basic structure — rows, columns, data types, and statistics.

In [1]:
import pandas as pd

# Load the dataset
df = pd.read_csv("insurance.csv")
print("Dataset loaded successfully!")

Dataset loaded successfully!

## 1. head() output
Look at the first 5 rows of data.

In [2]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

## 2. Dataset shape
How many rows and columns are in the dataset.

In [3]:
df.shape

(1338, 7)

## 3. Column names

In [4]:
df.columns.tolist()

['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges']

## 4. Dataset information
Data types and non-null counts for each column.

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB

## 5. Statistical summary
Basic statistics (mean, min, max, etc.) for numeric columns.

In [6]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010